version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: challenge-db
    environment:
      POSTGRES_DB: challenge_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SUA_SENHA
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init-sql:/docker-entrypoint-initdb.d
